Numpy

In [1]:
import numpy as np

In [35]:
import math

### ***Let's do some basic stuff***

In [4]:
a = np.array(5)
a

array(5)

In [5]:
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [12]:
a.reshape(5,3)

In [15]:
a = a.reshape(5,3)

In [18]:
print(a.shape)
print(a.ndim)
print(a.size)
print(a.dtype)

(5, 3)
2
15
int64


## Some operatoin in Numpy


In [22]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [27]:
a = np.array([20,30,50,56])
b = np.arange(4)
a + b

array([20, 31, 52, 59])

In [31]:
a * b

array([  0,  30, 100, 168])

In [32]:
a @ b # Baraye zarbe matrixy hastesh

298

In [33]:
c = a + b

In [34]:
c > 46

array([False, False,  True,  True])

In [37]:
np.sin(c)

array([ 0.91294525, -0.40403765,  0.98662759,  0.63673801])